export {default as authRouter} from './auth.js'
export {default as categoriesRouter} from './category.js'
export {default as subCategoriesRouter} from './sub-category.js'
export {default as biddingProductsRouter} from './bidding-product.js'
export {default as biddingRecordRouter} from './bidding-record.js'
export {default as productsRouter} from './product.js'
export {default as requestUpgradeRouter} from './request-upgrade.js'
export {default as productDescriptionRouter} from './product-description.js'
